<?php
$this->headTitle('Strona kontaktowa');

#$this->mainMenu()->setActiveItemId('home');
/*
$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home')
            ]);
*/
$form->get('title')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Please contact with me'
    ]);

$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'name@example.com'
    ]);

$form->get('author')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'John Doe'
    ]);

$form->get('submit')->setAttributes(array(
    'class'=>'btn btn-primary'
    ));

$form->get('content')->setAttributes([
    'class'=>'form-control',
    'rows'=>6, 
    'placeholder'=>'Tekst'
    ]);
?>
<h1>Formularz kontaktowy</h1>

<div class="row">
    
    <div class="col-md-8">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('title')); ?>
            <?= $this->formElement($form->get('title')); ?>
            <?= $this->formElementErrors($form->get('title')); ?>

        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('author')); ?>
            <?= $this->formElement($form->get('author')); ?>
            <?= $this->formElementErrors($form->get('author')); ?>

        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>

        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('content')); ?>
            <?= $this->formElement($form->get('content')); ?>
            <?= $this->formElementErrors($form->get('content')); ?>
        </div>
        
        <p class="hint">Zabezpieczenie</p>
        <?= $this->formElement($form->get('captcha')); ?>
        <?= $this->formElementErrors($form->get('captcha')); ?>
        <p class="hint">Wpisz litery i cyfry, które widzisz na obrazku.</p>
        <br>
        <?= $this->formElement($form->get('csrf')); ?>
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>

    </div>
</div>


