<?php
$this->headTitle('Pierwsza strona');

#$this->mainMenu()->setActiveItemId('home');
/*
$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home')
            ]);
*/
?>
<h1>Witaj na prywantej stronie</h1>

<div class="row">
    
    <div class="col-md-8">
   

    <h3>
    Welcome, Willkommen, Witaj
    </h3>
    
    <b>[PL]</b> Strona poświecona jest mojej pracy i zainteresowaniom. Jak pracuje i w jakie technologie liznąłem poczytasz poniżej, jest to strona prywatna, obecnie nie prowadze działanosci gospodarczej. Możesz się ze mną skontakować, aby powymieniac poglądy. Czym sie konkretnie zajmuje głównie informatyką oraz szeroko pojęta automatyką, znajdziesz wiecej info o mnie wertując tą stonę. Pozdrawiam Maciej 'pvalue'.
    </p>
    
    <p>
       
    <b>[EN]</b> The site is devoted to my work and interests. You can read about how I work and what technologies I learn in the section down. You can contact me to exchange views. What exactly does it mainly deal with computer science and broadly understood automation, you will find more info about me on this page. Regards Maciej 'pvalue'.    
       
    </p>
    <p>
    
    <b>[DE]</b> Die Seite ist meiner Arbeit und meinen Interessen gewidmet. Wie ich arbeite und welche Technologien ich lerne, können Sie im Abschnitt unten nachlesen. Sie können mich zum Meinungsaustausch kontaktieren. Was genau es hauptsächlich mit Informatik und allgemein verstandener Automatisierung zu tun hat, erfahren Sie auf dieser Seite mehr über mich. Grüße Maciej 'pvalue'.
    </p>


    </div>
</div>

<br><br>
