<?php

use Zend\Form\Element;

$title = 'Add site';
$this->headTitle($title);
?>
<script type="text/javascript" src="/public/js/mce_usta.js"></script>
<h2><?php echo $this->escapeHtml($title); ?></h2>

<?php

$form = $this->form;
$form->setAttribute('action', $this->url('content', array('action' => 'add')));
$form->prepare();

$element = new Element\Select('order');
$element->setLabel('Position: ');
$element->setValueOptions(array(
		'0' => 'Top',
		'1' => 'Main',
		'2' => 'Bottom',
));
$element->setValue('0');

//$this->navigation->setValue(null);

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('name'));
echo $this->formtextarea($form->get('sitecontent'));
echo '<br>';
echo "Link position: " . $this->formselect($element);
echo '<br>';
echo '<br>';
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag($form);

?>
