<?php
$this->headTitle('Tematy');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home')
            ]);
?>

<h1>Tematy mojego bloga</h1>
<p><strong>Blog prywatny</strong> - jest to blog moich przemyśleń i analiz. Nie jest zwiazany z moja pracą zawodową. Nie jest ścisły ani pragmatyczny, jest luźną rozmową z czytajacym!</p>
<br>
<div class="row">
    
    <div class="col-md-12">

    <?php foreach($posts as $post): ?>

    <h3>
        <a href="<?= $this->url('posts', ['action'=>'view', 'id'=>$post->getId()]); ?>">
            <?= $this->escapeHtml($post->getTitle()); ?>
        </a>    
    </h3>
        <br>
    <div class="row">
    <div class="col-md-3"><img src="<?= $this->basePath('/img/blog/mini/' . $this->escapeHtml($post->GetPict())); ?>">
    </div>
        <div class="col-md-6">
                <p style="text-indent:0px;">
                    Publikacja: <?= $this->escapeHtml(date('jS \of F Y', strtotime($post->getDateCreated()))); ?> <br>
                    Autor: <i><?= $this->escapeHtml($post->getAutor());?> </i>
                    <br>
                    Tagi: <?= $this->escapeHtml($postManager->convertTagsToString($post)); ?>
                </p>    
                    
                <p class="comments-header">
                    <?= $this->escapeHtml($postManager->getCommentCountStr($post)); ?> | 
                    <a href="<?= $this->url('posts', ['action'=>'view', 'id'=>$post->getId()],
                            ['fragment'=>'komentarz']); ?>">
                        Dodaj nowy komentarz
                    </a>
                </p>
        </div>
    </div>
    <br><br>
    <p>    
        <?= $this->escapeHtml(substr($post->getContent(), 0, 768)); ?>
    </p>
    <div style="float: right">
    <a class="btn btn-info" href="<?= $this->url('posts', 
                    ['action'=>'view', 'id'=>$post->getId()]); ?>">
    <span class="glyphicon glyphicon-pencil" ></span> Więcej...
    </a>
    </div>
    <br><br>


    <?php endforeach; ?>

    <?= $this->paginationControl($posts,
                    'Sliding',
                    'blog/partial/paginator', 
                    array('route' => 'Blog')); ?>
    
    </div>


</div>


