<div class="jumbotron">
    <h1><span class="zf-green">Usuwanie Użytkownika</span></h1>

    <p>
        Potwierdź usunięcie użytkownika: "<?= $user->getUsername() ?>"
    </p>
    <form action="<?= $this->url('users', ['action' => 'delete', 'id' => $id]) ?>" method="post">
        <div class="form-group">
            <input type="hidden" name="id" value="<?= (int) $user->getId() ?>" />
            <input type="submit" class="btn btn-danger" name="del" value="Usuń" />
            <input type="submit" class="btn btn-success" name="del" value="Anuluj" />
        </div>
    </form>
</div>
