<?php
$this->headTitle('Zarządzanie artykułami');

$this->pageBreadcrumbs()->setItems([
            'Admin'=>$this->url('home')
            ]);
?>

<h1>Zarządzanie artykułami</h1>

<p>
<a class="btn btn-default" href="
    <?= $this->url('articles', ['action'=>'add']); ?>">
    Dodaj artykuł
</a>
</p>

<table class="table table-striped">

   <tr>
        <th>ID</th>
        <th>Tytuł artykułu</th>
        <th>Data utworzenia</th>
        <th>Autor</th>
        <th>Status</th>        
        <th>Akcje</th>        
    </tr>
    
    <?php foreach ($articles as $post): ?>
    
    <tr>
        <td><?= $this->escapeHtml($post->getId()); ?></td>
        <td>
            <a href="<?= $this->url('articles', ['action'=>'view', 'id'=>$post->getId()]); ?>">
                <?= $this->escapeHtml($post->getTitle()); ?>
            </a> 
        </td>
        <td><?= $this->escapeHtml($post->getDateCreated()); ?></td>        
        <td><?= $this->escapeHtml($post->getAutor()); ?></td>        
        <td><?= $this->escapeHtml($articlesManager->getPostStatusAsString($post)); ?></td>
        <td>
            <a class="btn btn-info" href="<?= $this->url('articles',
                    ['action'=>'edit', 'id'=>$post->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Edit
            </a>
            <a class="btn btn-danger" href="<?= $this->url('articles',
                    ['action'=>'delete', 'id'=>$post->getId()]); ?>">
                <span class="glyphicon glyphicon-remove"></span> Delete
            </a>
        </td>    
    </tr>
        
    <?php endforeach; ?>   
    
</table>